### ISSUE TITLE
How to actually import

### ISSUE THREAD

**Issue by steowens** [jfmdev/aFileDialog#4]
Using latest android studio.  Can't find any way to import your library that actually builds.

**Comment by jfmdev** [comment]
Hi Steve,
- Can you tell which is the error that Android Studio throws when trying to build the library?
- Have you tried to build the demo project?

**Comment by jfmdev** [comment]
Closed due to inactivity.
If you do not know how to import a library in Android Studio, you can check StackOverflow: http://stackoverflow.com/questions/16588064/how-do-i-add-a-library-project-to-the-android-studio

**Comment by hiro2016** [comment]
Leaving a little note since I'm new to android and got caught on the topic too.

Note1:
Edit "settings.gradle" and "build.gradle"(the one under "your_project_name/app" folder). Android studio GUI changes too often. http://stackoverflow.com/questions/16588064/how-do-i-add-a-library-project-to-the-android-studio was a good resource, although reading the demo was the best.

Note2:
After git clone "https://github.com/jfmdev/aFileDialog.git", copy the folder "/aFileDialog/library/app" into your libs folder or a location of your choice. Coping the library folder results in "Configuration with name default not found".

Note3:
"Error:Execution failed for task ':aFileDialog:processReleaseResources'. > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/d/Android/Sdk/build-tools/22.0.1/aapt'' finished with non-zero exit value 127"
Idk but the magic commands below seems to do the trick(I'm using ubuntu):
sudo apt-get install -y lib32ncurses5 lib32gomp1 lib32z1-dev
sudo apt-get install -y lib32gcc1 libc6-i386 lib32z1 lib32stdc++6

Note4:
"Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed with multiple errors, see logs"
> http://stackoverflow.com/questions/17587751/gradle-execution-failed-for-task-processdebugmanifest

Check the gradle console:
"Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:6:5-22:19 to override/"

add 'tools:replace="android:icon,android:label"' to the application tag and 'xmlns:tools="http://schemas.android.com/tools"' to the manifest tag.

...Wow, android is so hard!
Thanks for an interesting library.
