### ISSUE TITLE
Restricting User

### ISSUE THREAD

**Issue by ECD00UFA** [jfmdev/aFileDialog#5]
Hey there. Hope you are doing well.

i was wondering there should have been a way to restrict user to back from the start directory defined using FileChooserActivity.INPUT_START_FOLDER or else the User would be able to go to the root directory if i'm not wrong?

Sorry For my BAD ENGLISH.

**Comment by jfmdev** [comment]
Hello,

The library do not includes any feature for restrict the folders in which the user can navigate. However, it's a good idea, so I'm going to added to the next release (probably in one or two months).

In the meantime, you could implement it yourself: you only have to modify the method `loadFolder()` from the class `FileChooserCore`.

Particularly, you should check the lines:

``` java
// Add the parent folder.
if(this.currentFolder.getParent() != null) {
  File parent = new File(this.currentFolder.getParent());
  if(parent.exists()) {
    fileItems.add(new FileItem(this.chooser.getContext(), parent, ".."));                   
  }
}
```

In the line `if(parent.exists())` you could add another condition, in order to verify that the user is not already in the _start folder_ (an avoid adding the `..` element on the view)..

**Comment by ECD00UFA** [comment]
thank you for your response...

I'll surely be giving it a try and let you know if there is a breakthrough..

**Comment by jfmdev** [comment]
I have implemented a new feature that allows to use _regular expressions_ to define which folders can be selected (previously to this, only files could be filtered using regexp).

So you can restrict the user to no go back from the start directory, by setting a filter that only accepts folders whose absolute path starts with the start directory.

For example:

``` java
Intent intent = new Intent(this, FileChooserActivity.class);
intent.putExtra(FileChooserActivity.INPUT_REGEX_FOLDER_FILTER, "^(/storage/sdcard/)(.*)");
this.startActivityForResult(intent, 0);
```
